<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.054" timestamp="2021-03-23T15:29:24.895827" hostname="L01015057.local"><testcase classname="test1" name="test_one" time="0.001" /><testcase classname="test1.TestNodeId" name="test_one" time="0.001" /><testcase classname="test1.TestNodeId" name="test_two[1-1]" time="0.001" /><testcase classname="test1.TestNodeId" name="test_two[3-4]" time="0.002"><failure message="assert 3 == 4">self = &lt;test1.TestNodeId object at 0x10870c190&gt;, x = 3, y = 4

    @pytest.mark.parametrize('x,y', [(1, 1), (3, 4)])
    def test_two(self, x, y):
        print(f'TestNodeId::test_two::{x} == {y}')
&gt;       assert x == y
E       assert 3 == 4

test1.py:16: AssertionError</failure></testcase></testsuite></testsuites>